language: python
python:
  - "2.7"
system_site_packages: true
sudo: false
install:
  - pip install flake8 --use-mirrors
  #- pip install pylint --use-mirrors
  #- pip install nose --use-mirrors
script:
  - flake8 --show-source --show-pep8 datapath/*/* lib/* overlay/etc/xapi.d/plugins/* volume/*/*
  #- pylint lib datapath volume
  #- nosetests
